# Generated by Django 4.0.3 on 2022-04-05 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='Customer status',
        ),
    ]
