# Generated by Django 4.0.3 on 2022-04-05 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_customer_alter_combo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeddingServiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date_of_booking', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeddingServiceReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('number_of_table', models.IntegerField()),
                ('groom_name', models.CharField(max_length=100)),
                ('bride_name', models.CharField(max_length=100)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.combo')),
                ('wedding_service_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.weddingservicereceipt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='combo',
            field=models.ManyToManyField(related_name='receipts', through='wedding.WeddingServiceReceiptDetail', to='wedding.combo'),
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='wedding.customer'),
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='date_of_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='wedding.dateoforganization'),
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='wedding.hall'),
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='service',
            field=models.ManyToManyField(related_name='receipts', to='wedding.service'),
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
