# Generated by Django 4.0.3 on 2022-04-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_dateoforganization_service_weddingservicereceipt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateoforganization',
            unique_together={('day', 'month', 'year')},
        ),
    ]
