# Generated by Django 4.0.3 on 2022-04-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_timeframe_dateoforganization_time_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateoforganization',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='weddingservicereceipt',
            name='time_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='wedding.timeframe'),
        ),
    ]
